Update qtcreator docs
cqse/teamscale-cli pull request #14
Opened 2020-05-18 09:58 UTC by AnonymFx

2020-05-18 14:55 UTC, karottenreibe approved these changes

2020-05-18 14:57 UTC, karottenreibe requested changes
sorry, I just saw that all builds are breaking because of some libgit problem. Can you check please?

2020-05-26 17:41 UTC, AnonymFx commented
Build was failing a while now, fixed on master w/ the help of @nihathrael and merged into this branch.

2020-06-08 14:06 UTC, AnonymFx commented
@karottenreibe Do you mind if merge this? Build is working now and afaik there were no other review comments, right?

2020-06-12 11:26 UTC, merged